Upgrade dependencies
Removed @js-temporal/polyfill because CLJS build was failing with the following error:

shadow-cljs - running: lein with-profile +cljs run -m shadow.cljs.devtools.cli --npm release frontend
[:frontend] Compiling ...
failed to convert sources
{:tag :shadow.build.closure/convert-error, :sources [[:shadow.build.npm/resource "node_modules/jsbi/dist/jsbi-umd.js"] [:shadow.build.npm/resource "node_modules/@js-temporal/polyfill/dist/index.cjs"] [:shadow.build.npm/resource "node_modules/react/cjs/react.production.min.js"] [:shadow.build.npm/resource "node_modules/react/cjs/react.development.js"] [:shadow.build.npm/resource "node_modules/react/index.js"] [:shadow.build.npm/resource "node_modules/scheduler/cjs/scheduler.production.min.js"] [:shadow.build.npm/resource "node_modules/scheduler/cjs/scheduler.development.js"] [:shadow.build.npm/resource "node_modules/scheduler/index.js"] [:shadow.build.npm/resource "node_modules/react-dom/cjs/react-dom.production.min.js"] [:shadow.build.npm/resource "node_modules/react-dom/cjs/react-dom.development.js"] [:shadow.build.npm/resource "node_modules/react-dom/index.js"]]}
ExceptionInfo: failed to convert sources
	shadow.build.closure/convert-sources-simple*/fn--15007 (closure.clj:2077)
	shadow.build.closure/convert-sources-simple* (closure.clj:2064)
	shadow.build.closure/convert-sources-simple* (closure.clj:1928)
	shadow.build.closure/convert-sources-simple (closure.clj:2238)
	shadow.build.closure/convert-sources-simple (closure.clj:2188)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1245)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1238)
	shadow.build.compiler/compile-all (compiler.clj:1494)
	shadow.build.compiler/compile-all (compiler.clj:1357)
	shadow.build.api/compile-sources (api.clj:261)
	shadow.build.api/compile-sources (api.clj:253)
	shadow.build/compile (build.clj:512)
	shadow.build/compile (build.clj:493)
	shadow.cljs.devtools.api/release* (api.clj:338)
	shadow.cljs.devtools.api/release* (api.clj:324)
	shadow.cljs.devtools.cli-actual/do-build-command (cli_actual.clj:28)
	shadow.cljs.devtools.cli-actual/do-build-command (cli_actual.clj:25)
	shadow.cljs.devtools.cli-actual/do-build-commands (cli_actual.clj:49)
	shadow.cljs.devtools.cli-actual/do-build-commands (cli_actual.clj:38)
	shadow.cljs.devtools.cli-actual/main/body-fn--18718--auto----19427 (cli_actual.clj:166)
	shadow.cljs.devtools.cli-actual/main (cli_actual.clj:165)
	shadow.cljs.devtools.cli-actual/main (cli_actual.clj:132)
	clojure.core/apply (core.clj:671)
	clojure.core/apply (core.clj:662)
	shadow.cljs.devtools.cli-actual/-main (cli_actual.clj:219)
	shadow.cljs.devtools.cli-actual/-main (cli_actual.clj:217)
	clojure.lang.Var.applyTo (Var.java:705)
	clojure.core/apply (core.clj:667)
	clojure.core/apply (core.clj:662)
	shadow.cljs.devtools.cli/-main (cli.clj:75)
	shadow.cljs.devtools.cli/-main (cli.clj:67)
	clojure.lang.Var.invoke (Var.java:393)
	user/eval144 (form-init14783016850177704842.clj:1)
	user/eval144 (form-init14783016850177704842.clj:1)
	clojure.lang.Compiler.eval (Compiler.java:7194)
	clojure.lang.Compiler.eval (Compiler.java:7184)
	clojure.lang.Compiler.load (Compiler.java:7653)
	clojure.lang.Compiler.loadFile (Compiler.java:7591)
	clojure.main/load-script (main.clj:475)
	clojure.main/init-opt (main.clj:477)
	clojure.main/init-opt (main.clj:477)
	clojure.main/initialize (main.clj:508)
	clojure.main/null-opt (main.clj:542)
	clojure.main/null-opt (main.clj:539)
	clojure.main/main (main.clj:664)
	clojure.main/main (main.clj:616)
	clojure.lang.Var.applyTo (Var.java:705)
	clojure.main.main (main.java:40)
Caused by:
IllegalStateException: Expected a property access or array pattern: OBJECT_PATTERN 2:4095  [length: 33] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs]
    STRING_KEY years 2:4095  [length: 5] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs]
        NAME t$jscomp$510 2:4095  [length: 1] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs] [original_name: t]
    STRING_KEY months 2:4095  [length: 6] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs]
        NAME o$jscomp$298 2:4095  [length: 1] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs] [original_name: o]
    STRING_KEY weeks 2:4095  [length: 5] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs]
        NAME n$jscomp$282 2:4095  [length: 1] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs] [original_name: n]
    STRING_KEY days 2:4095  [length: 4] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs]
        NAME r$jscomp$172 2:4095  [length: 1] [source_file: node_modules/@js-temporal/polyfill/dist/index.cjs] [original_name: r]

	com.google.javascript.jscomp.ExpressionDecomposer.exposeExpression (ExpressionDecomposer.java:230)
	com.google.javascript.jscomp.ExpressionDecomposer.exposeExpression (ExpressionDecomposer.java:156)
	com.google.javascript.jscomp.ExpressionDecomposer.maybeExposeExpression (ExpressionDecomposer.java:136)
	com.google.javascript.jscomp.FunctionInjector$CallSiteType$6.prepare (FunctionInjector.java:476)
	com.google.javascript.jscomp.FunctionInjector.maybePrepareCall (FunctionInjector.java:548)
	com.google.javascript.jscomp.InlineFunctions.decomposeExpressions (InlineFunctions.java:792)
	com.google.javascript.jscomp.InlineFunctions.process (InlineFunctions.java:148)
	com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process (PhaseOptimizer.java:240)
	com.google.javascript.jscomp.PhaseOptimizer$Loop.process (PhaseOptimizer.java:378)
	com.google.javascript.jscomp.PhaseOptimizer.process (PhaseOptimizer.java:179)
	com.google.javascript.jscomp.Compiler.performTranspilationAndOptimizations (Compiler.java:2933)
	com.google.javascript.jscomp.Compiler.lambda$stage2Passes$6 (Compiler.java:996)
	com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread (CompilerExecutor.java:126)
	com.google.javascript.jscomp.Compiler.runInCompilerThread (Compiler.java:1044)
	com.google.javascript.jscomp.Compiler.stage2Passes (Compiler.java:993)
	com.google.javascript.jscomp.Compiler.compile (Compiler.java:876)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
	jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke (Method.java:568)
	clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:167)
	clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:102)
	shadow.build.closure/convert-sources-simple*/fn--15007/fn--15008 (closure.clj:2067)
	shadow.build.closure/convert-sources-simple*/fn--15007 (closure.clj:2065)
	shadow.build.closure/convert-sources-simple* (closure.clj:2064)
	shadow.build.closure/convert-sources-simple* (closure.clj:1928)
	shadow.build.closure/convert-sources-simple (closure.clj:2238)
	shadow.build.closure/convert-sources-simple (closure.clj:2188)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1245)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1238)
	shadow.build.compiler/compile-all (compiler.clj:1494)
	shadow.build.compiler/compile-all (compiler.clj:1357)
	shadow.build.api/compile-sources (api.clj:261)
	shadow.build.api/compile-sources (api.clj:253)
	shadow.build/compile (build.clj:512)
	shadow.build/compile (build.clj:493)
	shadow.cljs.devtools.api/release* (api.clj:338)
	shadow.cljs.devtools.api/release* (api.clj:324)
	shadow.cljs.devtools.cli-actual/do-build-command (cli_actual.clj:28)
	shadow.cljs.devtools.cli-actual/do-build-command (cli_actual.clj:25)
	shadow.cljs.devtools.cli-actual/do-build-commands (cli_actual.clj:49)
	shadow.cljs.devtools.cli-actual/do-build-commands (cli_actual.clj:38)
	shadow.cljs.devtools.cli-actual/main/body-fn--18718--auto----19427 (cli_actual.clj:166)
	shadow.cljs.devtools.cli-actual/main (cli_actual.clj:165)
	shadow.cljs.devtools.cli-actual/main (cli_actual.clj:132)
	clojure.core/apply (core.clj:671)
	clojure.core/apply (core.clj:662)
	shadow.cljs.devtools.cli-actual/-main (cli_actual.clj:219)
	shadow.cljs.devtools.cli-actual/-main (cli_actual.clj:217)
	clojure.lang.Var.applyTo (Var.java:705)
	clojure.core/apply (core.clj:667)
	clojure.core/apply (core.clj:662)
	shadow.cljs.devtools.cli/-main (cli.clj:75)
	shadow.cljs.devtools.cli/-main (cli.clj:67)
	clojure.lang.Var.invoke (Var.java:393)
	user/eval144 (form-init14783016850177704842.clj:1)
	user/eval144 (form-init14783016850177704842.clj:1)
	clojure.lang.Compiler.eval (Compiler.java:7194)
	clojure.lang.Compiler.eval (Compiler.java:7184)
	clojure.lang.Compiler.load (Compiler.java:7653)
	clojure.lang.Compiler.loadFile (Compiler.java:7591)
	clojure.main/load-script (main.clj:475)
	clojure.main/init-opt (main.clj:477)
	clojure.main/init-opt (main.clj:477)
	clojure.main/initialize (main.clj:508)
	clojure.main/null-opt (main.clj:542)
	clojure.main/null-opt (main.clj:539)
	clojure.main/main (main.clj:664)
	clojure.main/main (main.clj:616)
	clojure.lang.Var.applyTo (Var.java:705)
	clojure.main.main (main.java:40)